rules:
  # Rule Name
  ensure-info-title:
    description: Info object must have a title
    message: "The API must have a title defined."
    given: "$.info"
    severity: error
    then:
      field: title
      function: truthy # Built-in function: value must not be empty, null, or false

